# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Flash Chat' do
  use_frameworks!

  # Pods for Flash Chat
  pod 'CLTypingLabel', '~> 0.4.0'
  pod 'Firebase/Auth', '~> 8.9.1'
  pod 'Firebase/Firestore', '~> 8.9.1'

  # ignore all warnings from all pods
  inhibit_all_warnings!

end
